export const cityAreas = {
  // Amman: ["Abdoun", "Jabal Al Weibdeh", "Khalda", "Sweifieh", "Al Gardens"],
  Irbid: [
    {
      values: [
        {
          id: "6",
          label: "اربد (171)",
          icon: null,
          search_field: "اربد (171) irbid (171)",
          group_label: null,
          alhodlist: [
            {
              id: "8",
              label: "البقعة (6)",
              icon: null,
              search_field: "البقعه (6) al-baqa'a (6)",
              group_label: null,
            },
            {
              id: "14",
              label: "البلد (8)",
              icon: null,
              search_field: "البلد (8) al-balad (8)",
              group_label: null,
            },
            {
              id: "42",
              label: "الحميرا الشرقية (22)",
              icon: null,
              search_field: "الحميرا الشرقيه (22) al-humayra al-sharqiya (22)",
              group_label: null,
            },
            {
              id: "46",
              label: "الحميرا الغربية (23)",
              icon: null,
              search_field: "الحميرا الغربيه (23) al-humayra al-gharbiya (23)",
              group_label: null,
            },
            {
              id: "50",
              label: "الدوار (28)",
              icon: null,
              search_field: "الدوار (28) al-dwar (28)",
              group_label: null,
            },
            {
              id: "54",
              label: "السريج (26)",
              icon: null,
              search_field: "السريج (26) al-sareej (26)",
              group_label: null,
            },
            {
              id: "70",
              label: "السياف (1)",
              icon: null,
              search_field: "السياف (1) al-sayyaf (1)",
              group_label: null,
            },
            {
              id: "74",
              label: "الشيخ خليل (14)",
              icon: null,
              search_field: "الشيخ خليل (14) al-shaikh khaleel (14)",
              group_label: null,
            },
            {
              id: "78",
              label: "الصبيح (10)",
              icon: null,
              search_field: "الصبيح (10) al-sbeih (10)",
              group_label: null,
            },
            {
              id: "84",
              label: "الطوال (21)",
              icon: null,
              search_field: "الطوال (21) al-tawal (21)",
              group_label: null,
            },
            {
              id: "88",
              label: "الطورى (2)",
              icon: null,
              search_field: "الطوري (2) al-toora (2)",
              group_label: null,
            },
            {
              id: "92",
              label: "العريف (29)",
              icon: null,
              search_field: "العريف (29) al-areef (29)",
              group_label: null,
            },
            {
              id: "96",
              label: "القصيله (17)",
              icon: null,
              search_field: "القصيله (17) al-qasila (17)",
              group_label: null,
            },
            {
              id: "100",
              label: "الكروم (18)",
              icon: null,
              search_field: "الكروم (18) al-koroom (18)",
              group_label: null,
            },
            {
              id: "104",
              label: "المردمه الجنوبية (5)",
              icon: null,
              search_field: "المردمه الجنوبيه (5) al-mardamah al-janoubiya (5)",
              group_label: null,
            },
            {
              id: "108",
              label: "المردمه الشمالية (3)",
              icon: null,
              search_field: "المردمه الشماليه (3) al-mardamah al-shamaliya (3)",
              group_label: null,
            },
            {
              id: "112",
              label: "المسبغانية الجنوبية (11)",
              icon: null,
              search_field:
                "المسبغانيه الجنوبيه (11) al-masbaghaniya al-janoubiya (11)",
              group_label: null,
            },
            {
              id: "116",
              label: "المسبغانية الشمالية (7)",
              icon: null,
              search_field:
                "المسبغانيه الشماليه (7) al-masbaghaniya al-shamaliya (7)",
              group_label: null,
            },
            {
              id: "120",
              label: "المطلع (9)",
              icon: null,
              search_field: "المطلع (9) al-matla' (9)",
              group_label: null,
            },
            {
              id: "124",
              label: "المعترض  الشرقي (15)",
              icon: null,
              search_field: "المعترض  الشرقي (15) al-mo'tarid al-sharqi (15)",
              group_label: null,
            },
            {
              id: "128",
              label: "المعترض الغربي (16)",
              icon: null,
              search_field: "المعترض الغربي (16) al-mo'tarid al-gharbi (16)",
              group_label: null,
            },
            {
              id: "132",
              label: "خربة قاسم (25)",
              icon: null,
              search_field: "خربه قاسم (25) khirbat qasim (25)",
              group_label: null,
            },
            {
              id: "136",
              label: "غابة جرن الغزال (24)",
              icon: null,
              search_field: "غابه جرن الغزال (24) ghabat jirn al-ghazal (24)",
              group_label: null,
            },
            {
              id: "140",
              label: "قروق الجنوبي (20)",
              icon: null,
              search_field: "قروق الجنوبي (20) qrooq al-janoubi (20)",
              group_label: null,
            },
            {
              id: "148",
              label: "قروق الشرقي (12)",
              icon: null,
              search_field: "قروق الشرقي (12) qrooq al-sharqi (12)",
              group_label: null,
            },
            {
              id: "154",
              label: "قروق الغربي (13)",
              icon: null,
              search_field: "قروق الغربي (13) qrooq al-gharbi (13)",
              group_label: null,
            },
            {
              id: "158",
              label: "كعبير (19)",
              icon: null,
              search_field: "كعبير (19) ka'beer (19)",
              group_label: null,
            },
            {
              id: "162",
              label: "وادي جرن الغزال (27)",
              icon: null,
              search_field: "وادي جرن الغزال (27) wadi jirn al-ghazal (27)",
              group_label: null,
            },
            {
              id: "168",
              label: "وراء التل (4)",
              icon: null,
              search_field: "وراء التل (4) wara'a al-tal (4)",
              group_label: null,
            },
          ],
        },
        {
          id: "172",
          label: "اسعره (172)",
          icon: null,
          search_field: "اسعره (172) as'ara (172)",
          group_label: null,
          alhodlist: [  {
            "id": "174",
            "label": "البلد (7)",
            "icon": null,
            "search_field": "البلد (7) al-balad (7)",
            "group_label": null
        },
        {
            "id": "196",
            "label": "الحصيد (1)",
            "icon": null,
            "search_field": "الحصيد (1) al-haseed (1)",
            "group_label": null
        },
        {
            "id": "200",
            "label": "الدريجات (8)",
            "icon": null,
            "search_field": "الدريجات (8) al-dreijat (8)",
            "group_label": null
        },
        {
            "id": "204",
            "label": "الدقانه (4)",
            "icon": null,
            "search_field": "الدقانه (4) al-daqqana (4)",
            "group_label": null
        },
        {
            "id": "208",
            "label": "المنصيه (6)",
            "icon": null,
            "search_field": "المنصيه (6) al-mansiyah (6)",
            "group_label": null
        },
        {
            "id": "212",
            "label": "الميدان (2)",
            "icon": null,
            "search_field": "الميدان (2) al-midan (2)",
            "group_label": null
        },
        {
            "id": "216",
            "label": "النقار (9)",
            "icon": null,
            "search_field": "النقار (9) al-naqar (9)",
            "group_label": null
        },
        {
            "id": "220",
            "label": "ام العقارب (3)",
            "icon": null,
            "search_field": "ام العقارب (3) um al-aqarib (3)",
            "group_label": null
        },
        {
            "id": "224",
            "label": "ام خروبة (5)",
            "icon": null,
            "search_field": "ام خروبه (5) um kharooba (5)",
            "group_label": null
        }],
        },
        {
          id: "228",
          label: "البارحه (174)",
          icon: null,
          search_field: "البارحه (174) al-barha (174)",
          group_label: null,
          alhodlist: [  {
            "id": "230",
            "label": "ابان (4)",
            "icon": null,
            "search_field": "ابان (4) iban (4)",
            "group_label": null
        },
        {
            "id": "236",
            "label": "ابو اللجا (13)",
            "icon": null,
            "search_field": "ابو اللجا (13) abu al-laja (13)",
            "group_label": null
        },
        {
            "id": "240",
            "label": "اتساسيه (3)",
            "icon": null,
            "search_field": "اتساسيه (3) atsasiya (3)",
            "group_label": null
        },
        {
            "id": "264",
            "label": "البقعة الشرقية (5)",
            "icon": null,
            "search_field": "البقعه الشرقيه (5) al-baqa'a al-sharqiya (5)",
            "group_label": null
        },
        {
            "id": "268",
            "label": "البقعة الغربية (7)",
            "icon": null,
            "search_field": "البقعه الغربيه (7) al-baqa'a al-gharbiya (7)",
            "group_label": null
        },
        {
            "id": "272",
            "label": "البقعة الوسطى (6)",
            "icon": null,
            "search_field": "البقعه الوسطي (6) al-baqa'a al-wusta (6)",
            "group_label": null
        },
        {
            "id": "278",
            "label": "البلد (10)",
            "icon": null,
            "search_field": "البلد (10) al-balad (10)",
            "group_label": null
        },
        {
            "id": "304",
            "label": "الطوال (11)",
            "icon": null,
            "search_field": "الطوال (11) al-tawal (11)",
            "group_label": null
        },
        {
            "id": "308",
            "label": "المطارق (2)",
            "icon": null,
            "search_field": "المطارق (2) al-matariq (2)",
            "group_label": null
        },
        {
            "id": "318",
            "label": "المطلع (9)",
            "icon": null,
            "search_field": "المطلع (9) al-matla' (9)",
            "group_label": null
        },
        {
            "id": "322",
            "label": "المعلقة (8)",
            "icon": null,
            "search_field": "المعلقه (8) al-ma'alaqa (8)",
            "group_label": null
        },
        {
            "id": "326",
            "label": "المواجه (14)",
            "icon": null,
            "search_field": "المواجه (14) al-mwajih (14)",
            "group_label": null
        },
        {
            "id": "330",
            "label": "بستان المطلع (12)",
            "icon": null,
            "search_field": "بستان المطلع (12) bustan al-matla' (12)",
            "group_label": null
        },
        {
            "id": "334",
            "label": "حنينه (1)",
            "icon": null,
            "search_field": "حنينه (1) hunainah (1)",
            "group_label": null
        }],
        },
        {
          id: "338",
          label: "الحصن (175)",
          icon: null,
          search_field: "الحصن (175) al-huson (175)",
          group_label: null,
          alhodlist: [{
            "id": "340",
            "label": "ابو السوس (38)",
            "icon": null,
            "search_field": "ابو السوس (38) abu al-soos (38)",
            "group_label": null
        },
        {
            "id": "344",
            "label": "البطام الجنوبي (34)",
            "icon": null,
            "search_field": "البطام الجنوبي (34) al-batam al-janoubi (34)",
            "group_label": null
        },
        {
            "id": "348",
            "label": "البطام الشمالي (33)",
            "icon": null,
            "search_field": "البطام الشمالي (33) al-batam al-shamali (33)",
            "group_label": null
        },
        {
            "id": "352",
            "label": "البلد (12)",
            "icon": null,
            "search_field": "البلد (12) al-balad (12)",
            "group_label": null
        },
        {
            "id": "364",
            "label": "الجبيل الشرقي (3)",
            "icon": null,
            "search_field": "الجبيل الشرقي (3) al-jbeil al-sharqi (3)",
            "group_label": null
        },
        {
            "id": "368",
            "label": "الجبيل الغربي (4)",
            "icon": null,
            "search_field": "الجبيل الغربي (4) al-jbeil al-gharbi (4)",
            "group_label": null
        },
        {
            "id": "372",
            "label": "الجده (7)",
            "icon": null,
            "search_field": "الجده (7) al-jaddah (7)",
            "group_label": null
        },
        {
            "id": "376",
            "label": "الجلسات (27)",
            "icon": null,
            "search_field": "الجلسات (27) al-jalsat (27)",
            "group_label": null
        },
        {
            "id": "380",
            "label": "الحبيس (10)",
            "icon": null,
            "search_field": "الحبيس (10) al-hbeis (10)",
            "group_label": null
        },
        {
            "id": "384",
            "label": "الدهما الجنوبية (35)",
            "icon": null,
            "search_field": "الدهما الجنوبيه (35) al-dahma al-janoubiya (35)",
            "group_label": null
        },
        {
            "id": "388",
            "label": "الدهما الشمالية (25)",
            "icon": null,
            "search_field": "الدهما الشماليه (25) al-dahma al-shamaliya (25)",
            "group_label": null
        },
        {
            "id": "392",
            "label": "المراح وام الغزلان (29)",
            "icon": null,
            "search_field": "المراح وام الغزلان (29) al-marah wa um al-ghizlan (29)",
            "group_label": null
        },
        {
            "id": "396",
            "label": "المزاهر (28)",
            "icon": null,
            "search_field": "المزاهر (28) al-mazahir (28)",
            "group_label": null
        },
        {
            "id": "400",
            "label": "المقبيه (30)",
            "icon": null,
            "search_field": "المقبيه (30) al-maqbiya (30)",
            "group_label": null
        },
        {
            "id": "404",
            "label": "المومنيه (16)",
            "icon": null,
            "search_field": "المومنيه (16) al-momaniyah (16)",
            "group_label": null
        },
        {
            "id": "408",
            "label": "ام الابار الشرقية (1)",
            "icon": null,
            "search_field": "ام الابار الشرقيه (1) um al-abar al-sharqiya (1)",
            "group_label": null
        },
        {
            "id": "412",
            "label": "ام الابار الغربية (2)",
            "icon": null,
            "search_field": "ام الابار الغربيه (2) um al-abar al-sharqiya (2)",
            "group_label": null
        },
        {
            "id": "416",
            "label": "بركه و المطله (18)",
            "icon": null,
            "search_field": "بركه و المطله (18) baraka wa al-matallah (18)",
            "group_label": null
        },
        {
            "id": "420",
            "label": "بيارة العسل (37)",
            "icon": null,
            "search_field": "بياره العسل (37) bayarat al-asal (37)",
            "group_label": null
        },
        {
            "id": "424",
            "label": "بيضاة السلالم (32)",
            "icon": null,
            "search_field": "بيضاه السلالم (32) beidat al-salalim (32)",
            "group_label": null
        },
        {
            "id": "428",
            "label": "بين الحارات (24)",
            "icon": null,
            "search_field": "بين الحارات (24) bein al-harat (24)",
            "group_label": null
        },
        {
            "id": "432",
            "label": "خربة الطيارة (26)",
            "icon": null,
            "search_field": "خربه الطياره (26) khirbat al-tayyara (26)",
            "group_label": null
        },
        {
            "id": "436",
            "label": "خلايا وادي العين (31)",
            "icon": null,
            "search_field": "خلايا وادي العين (31) khalaya wadi al-ein (31)",
            "group_label": null
        },
        {
            "id": "440",
            "label": "دبات  ابو النصر (9)",
            "icon": null,
            "search_field": "دبات  ابو النصر (9) dobbat abu al-nasr (9)",
            "group_label": null
        },
        {
            "id": "444",
            "label": "راكسه وام الهوى (14)",
            "icon": null,
            "search_field": "راكسه وام الهوي (14) raksah wa um al-hawa (14)",
            "group_label": null
        },
        {
            "id": "448",
            "label": "سعوه و السرج (5)",
            "icon": null,
            "search_field": "سعوه و السرج (5) sa'wa wa al-sarj (5)",
            "group_label": null
        },
        {
            "id": "452",
            "label": "سلمى و الحوله (6)",
            "icon": null,
            "search_field": "سلمي و الحوله (6) salma wa al-hola (6)",
            "group_label": null
        },
        {
            "id": "456",
            "label": "شمشان (15)",
            "icon": null,
            "search_field": "شمشان (15) shamshan (15)",
            "group_label": null
        },
        {
            "id": "460",
            "label": "شوامر الحقاف (20)",
            "icon": null,
            "search_field": "شوامر الحقاف (20) shawamer al-haqaf (20)",
            "group_label": null
        },
        {
            "id": "464",
            "label": "صبحه (21)",
            "icon": null,
            "search_field": "صبحه (21) sabha (21)",
            "group_label": null
        },
        {
            "id": "468",
            "label": "طبول بوزه (11)",
            "icon": null,
            "search_field": "طبول بوزه (11) tobool booza (11)",
            "group_label": null
        },
        {
            "id": "472",
            "label": "طبول كوتيه (17)",
            "icon": null,
            "search_field": "طبول كوتيه (17) tobool kotyah (17)",
            "group_label": null
        },
        {
            "id": "476",
            "label": "ظهر الخربة (22)",
            "icon": null,
            "search_field": "ظهر الخربه (22) ghahr al-khirba (22)",
            "group_label": null
        },
        {
            "id": "480",
            "label": "عوجات  الطيارة (36)",
            "icon": null,
            "search_field": "عوجات  الطياره (36) ojat al-tayyara (36)",
            "group_label": null
        },
        {
            "id": "484",
            "label": "قطعة الاصبح (13)",
            "icon": null,
            "search_field": "قطعه الاصبح (13) qit'at al-asboh (13)",
            "group_label": null
        },
        {
            "id": "488",
            "label": "قطعة الصلاة (19)",
            "icon": null,
            "search_field": "قطعه الصلاه (19) qit'at al-salah (19)",
            "group_label": null
        },
        {
            "id": "492",
            "label": "مرجم الاحيمر (8)",
            "icon": null,
            "search_field": "مرجم الاحيمر (8) marjam al-ehaimer (8)",
            "group_label": null
        },
        {
            "id": "496",
            "label": "نومره و خديجة (39)",
            "icon": null,
            "search_field": "نومره و خديجه (39) nomara wa khadijah (39)",
            "group_label": null
        },
        {
            "id": "500",
            "label": "وقف بئر الزاغ (23)",
            "icon": null,
            "search_field": "وقف بئر الزاغ (23) khalat al-bi'ar (23)",
            "group_label": null
        }],
        },
        {
          id: "504",
          label: "الخراج (176)",
          icon: null,
          search_field: "الخراج (176) al-kharaj (176)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "560",
          label: "الصريح (177)",
          icon: null,
          search_field: "الصريح (177) al-sareeh (177)",
          group_label: null,
          alhodlist: [
            {
              id: "562",
              label: "ابو القاسم الجنوبي (16)",
              icon: null,
              search_field:
                "ابو القاسم الجنوبي (16) abu al-qasim al-janoubi (16)",
              group_label: null,
            },
            {
              id: "566",
              label: "ابو قاسم الشمالي (15)",
              icon: null,
              search_field: "ابو قاسم الشمالي (15) abu qasim al-shamali (15)",
              group_label: null,
            },
            {
              id: "570",
              label: "ارحيل الشرقي (12)",
              icon: null,
              search_field: "ارحيل الشرقي (12) arheel al-sharqi (12)",
              group_label: null,
            },
            {
              id: "574",
              label: "ارحيل الغربي (14)",
              icon: null,
              search_field: "ارحيل الغربي (14) arheel al-gharbi (14)",
              group_label: null,
            },
            {
              id: "580",
              label: "ارحيل الوسطاني (13)",
              icon: null,
              search_field: "ارحيل الوسطاني (13) arheel al-wastani (13)",
              group_label: null,
            },
            {
              id: "584",
              label: "الاريحا الجنوبية (5)",
              icon: null,
              search_field: "الاريحا الجنوبيه (5) al-ariha al-janoubiya (5)",
              group_label: null,
            },
            {
              id: "588",
              label: "الاريحا الشمالية (3)",
              icon: null,
              search_field: "الاريحا الشماليه (3) al-ariha al-shamaliya (3)",
              group_label: null,
            },
            {
              id: "592",
              label: "الاملس الجنوبي (23)",
              icon: null,
              search_field: "الاملس الجنوبي (23) al-amlas al-janoubi (23)",
              group_label: null,
            },
            {
              id: "596",
              label: "الاملس الشمالي (17)",
              icon: null,
              search_field: "الاملس الشمالي (17) al-amlas al-shamali (17)",
              group_label: null,
            },
            {
              id: "600",
              label: "البلد (59)",
              icon: null,
              search_field: "البلد (59) al-balad (59)",
              group_label: null,
            },
            {
              id: "622",
              label: "التلاوية الشرقية (49)",
              icon: null,
              search_field:
                "التلاويه الشرقيه (49) al-talawiya al-sharqiya (49)",
              group_label: null,
            },
            {
              id: "626",
              label: "التلاويه الغربية (50)",
              icon: null,
              search_field: "التلاويه الغربيه (50) al-talwiya al-gharbiya (50)",
              group_label: null,
            },
            {
              id: "630",
              label: "الجده و القطعة (60)",
              icon: null,
              search_field: "الجده و القطعه (60) al-jaddah wa al-qit'a (60)",
              group_label: null,
            },
            {
              id: "634",
              label: "الجزيرة (38)",
              icon: null,
              search_field: "الجزيره (38) al-jazeera (38)",
              group_label: null,
            },
            {
              id: "638",
              label: "الجوره (30)",
              icon: null,
              search_field: "الجوره (30) al-jorah (30)",
              group_label: null,
            },
            {
              id: "642",
              label: "الحمراء الشرقية (6)",
              icon: null,
              search_field: "الحمراء الشرقيه (6) al-hamraa al-sharqiya (6)",
              group_label: null,
            },
            {
              id: "646",
              label: "الحمراء الشرقية من الغربية (8)",
              icon: null,
              search_field:
                "الحمراء الشرقيه من الغربيه (8) al-hamraa al-sharqiya men al-gharbiya (8)",
              group_label: null,
            },
            {
              id: "650",
              label: "الحمراء الغربية (9)",
              icon: null,
              search_field: "الحمراء الغربيه (9) al-hamraa al-gharbiya (9)",
              group_label: null,
            },
            {
              id: "654",
              label: "الحمراء الغربية من الشرقية (7)",
              icon: null,
              search_field:
                "الحمراء الغربيه من الشرقيه (7) al-hamraa al-gharbiya men al-sharqiya (7)",
              group_label: null,
            },
            {
              id: "658",
              label: "الركية (22)",
              icon: null,
              search_field: "الركيه (22) al-rakiya (22)",
              group_label: null,
            },
            {
              id: "662",
              label: "الزقروطه (24)",
              icon: null,
              search_field: "الزقروطه (24) al-zaqroota (24)",
              group_label: null,
            },
            {
              id: "666",
              label: "الصدار (19)",
              icon: null,
              search_field: "الصدار (19) al-sadar (19)",
              group_label: null,
            },
            {
              id: "670",
              label: "الصدر الشمالي (31)",
              icon: null,
              search_field: "الصدر الشمالي (31) al-sadr al-janoubi (31)",
              group_label: null,
            },
            {
              id: "674",
              label: "الطوال الجنوبي الشرقي (41)",
              icon: null,
              search_field:
                "الطوال الجنوبي الشرقي (41) al-tawal al-janoubi al-sharqi (41)",
              group_label: null,
            },
            {
              id: "678",
              label: "الطوال الجنوبي الغربي (42)",
              icon: null,
              search_field:
                "الطوال الجنوبي الغربي (42) al-tawal al-janoubi al-gharbi (42)",
              group_label: null,
            },
            {
              id: "682",
              label: "الطوال الشمالي الشرقي (36)",
              icon: null,
              search_field:
                "الطوال الشمالي الشرقي (36) al-tawal al-shamali al-sharqi (36)",
              group_label: null,
            },
            {
              id: "686",
              label: "الطوال الشمالي الغربي (37)",
              icon: null,
              search_field:
                "الطوال الشمالي الغربي (37) al-tawal al-shamali al-ghatbi (37)",
              group_label: null,
            },
            {
              id: "690",
              label: "العكليك الجنوبي (51)",
              icon: null,
              search_field: "العكليك الجنوبي (51) al-'akleel al-janoubi (51)",
              group_label: null,
            },
            {
              id: "694",
              label: "العكليك الشمالي (39)",
              icon: null,
              search_field: "العكليك الشمالي (39) al-'akleel al-shamali (39)",
              group_label: null,
            },
            {
              id: "698",
              label: "العكليك الوسطاني (43)",
              icon: null,
              search_field: "العكليك الوسطاني (43) al-'akleek al-wastani (43)",
              group_label: null,
            },
            {
              id: "702",
              label: "القليعي الجنوبي (62)",
              icon: null,
              search_field: "القليعي الجنوبي (62) al-qlei'i al-janoubi (62)",
              group_label: null,
            },
            {
              id: "706",
              label: "القليعي الشمالي (61)",
              icon: null,
              search_field: "القليعي الشمالي (61) al-qlei'i al-shamali (61)",
              group_label: null,
            },
            {
              id: "710",
              label: "الماصية الجنوبية (29)",
              icon: null,
              search_field: "الماصيه الجنوبيه (29) al-masiah al-janoubiya (29)",
              group_label: null,
            },
            {
              id: "714",
              label: "الماصية الجنوبية الشرقية (34)",
              icon: null,
              search_field:
                "الماصيه الجنوبيه الشرقيه (34) al-masiah al-janoubiya al-sharqiya (34)",
              group_label: null,
            },
            {
              id: "718",
              label: "الماصية الجنوبية الغربية (35)",
              icon: null,
              search_field:
                "الماصيه الجنوبيه الغربيه (35) al-masiah al-janoubiya al-gharbiya (35)",
              group_label: null,
            },
            {
              id: "722",
              label: "الماصية الشمالية الشرقية (32)",
              icon: null,
              search_field:
                "الماصيه الشماليه الشرقيه (32) al-masiah al-shamaliya al-sharqiya (32)",
              group_label: null,
            },
            {
              id: "726",
              label: "الماصية الشمالية الغربية (33)",
              icon: null,
              search_field:
                "الماصيه الشماليه الغربيه (33) al-masiah al-shamaliya al-gharbiya (33)",
              group_label: null,
            },
            {
              id: "730",
              label: "الماصيه الشمالية (26)",
              icon: null,
              search_field: "الماصيه الشماليه (26) al-masiah al-shamaliya (26)",
              group_label: null,
            },
            {
              id: "734",
              label: "المراريط الشرقي (53)",
              icon: null,
              search_field: "المراريط الشرقي (53) al-marareet al-sharqi (53)",
              group_label: null,
            },
            {
              id: "738",
              label: "المراريط الغربية (54)",
              icon: null,
              search_field:
                "المراريط الغربيه (54) al-marareet al-gharbiya (54)",
              group_label: null,
            },
            {
              id: "742",
              label: "المراه (45)",
              icon: null,
              search_field: "المراه (45) al-marah (45)",
              group_label: null,
            },
            {
              id: "746",
              label: "المسرب الجنوبي (52)",
              icon: null,
              search_field: "المسرب الجنوبي (52) al-masrab al-janoubi (52)",
              group_label: null,
            },
            {
              id: "750",
              label: "المسرب الشمالي (40)",
              icon: null,
              search_field: "المسرب الشمالي (40) al-masrab al-shamali (40)",
              group_label: null,
            },
            {
              id: "754",
              label: "المسرب الوسطاني (44)",
              icon: null,
              search_field: "المسرب الوسطاني (44) al-masrab al-wastani (44)",
              group_label: null,
            },
            {
              id: "758",
              label: "المعترض  الشرقي (1)",
              icon: null,
              search_field: "المعترض  الشرقي (1) al-mo'tarid al-sharqi (1)",
              group_label: null,
            },
            {
              id: "762",
              label: "المعترض  الغربي (2)",
              icon: null,
              search_field: "المعترض  الغربي (2) al-mo'tarid al-gharbi (2)",
              group_label: null,
            },
            {
              id: "766",
              label: "الوعره (63)",
              icon: null,
              search_field: "الوعره (63) al-we'ra (63)",
              group_label: null,
            },
            {
              id: "770",
              label: "حور الجنوبي (20)",
              icon: null,
              search_field: "حور الجنوبي (20) hoor al-janoubi (20)",
              group_label: null,
            },
            {
              id: "774",
              label: "حور الشمالي (4)",
              icon: null,
              search_field: "حور الشمالي (4) hoor al-shamali (4)",
              group_label: null,
            },
            {
              id: "778",
              label: "حور الوسطاني (18)",
              icon: null,
              search_field: "حور الوسطاني (18) hoor al-wastani (18)",
              group_label: null,
            },
            {
              id: "782",
              label: "سعوى الجنوبي (58)",
              icon: null,
              search_field: "سعوي الجنوبي (58) sa'wa al-janoubi (58)",
              group_label: null,
            },
            {
              id: "786",
              label: "سعوى الشمالي (57)",
              icon: null,
              search_field: "سعوي الشمالي (57) sa'wa al-shamali (57)",
              group_label: null,
            },
            {
              id: "790",
              label: "سلما الشرقية (55)",
              icon: null,
              search_field: "سلما الشرقيه (55) salma al-sharqiya (55)",
              group_label: null,
            },
            {
              id: "794",
              label: "سلما الغربية (56)",
              icon: null,
              search_field: "سلما الغربيه (56) salma al-gharbiya (56)",
              group_label: null,
            },
            {
              id: "798",
              label: "سلمان الجنوبي (21)",
              icon: null,
              search_field: "سلمان الجنوبي (21) salman al-janoubi (21)",
              group_label: null,
            },
            {
              id: "814",
              label: "سلمان الشمالي (10)",
              icon: null,
              search_field: "سلمان الشمالي (10) salman al-shamali (10)",
              group_label: null,
            },
            {
              id: "818",
              label: "سلمان الوسطاني (11)",
              icon: null,
              search_field: "سلمان الوسطاني (11) salman al-wastani (11)",
              group_label: null,
            },
            {
              id: "822",
              label: "عنقاء الجنوبية (27)",
              icon: null,
              search_field: "عنقاء الجنوبيه (27) anqaa al-janoubiya (27)",
              group_label: null,
            },
            {
              id: "826",
              label: "عنقاء الشمالية (25)",
              icon: null,
              search_field: "عنقاء الشماليه (25) anqaa al-shamaliya (25)",
              group_label: null,
            },
            {
              id: "834",
              label: "مقاتي الركية (28)",
              icon: null,
              search_field: "مقاتي الركيه (28) maqati al-rakiya (28)",
              group_label: null,
            },
            {
              id: "838",
              label: "مقاتي الصدر الجنوبي (64)",
              icon: null,
              search_field:
                "مقاتي الصدر الجنوبي (64) maqati al-sadr al-janoubi (64)",
              group_label: null,
            },
            {
              id: "842",
              label: "مقاتي سعوه (46)",
              icon: null,
              search_field: "مقاتي سعوه (46) maqati sa'wa (46)",
              group_label: null,
            },
            {
              id: "846",
              label: "مقاتي قطعة الحجيه (47)",
              icon: null,
              search_field:
                "مقاتي قطعه الحجيه (47) maqati qita't al-hajiya (47)",
              group_label: null,
            },
          ],
        },
        {
          id: "850",
          label: "المغير (179)",
          icon: null,
          search_field: "المغير (179) al-mogheer (179)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "950",
          label: "النعيمه (180)",
          icon: null,
          search_field: "النعيمه (180) al-nuaiyymah (180)",
          group_label: null,
          alhodlist: [
            {
              id: "952",
              label: "ابو الحمام الشرقي (77)",
              icon: null,
              search_field:
                "ابو الحمام الشرقي (77) abu al-hamam al-sharqi (77)",
              group_label: null,
            },
            {
              id: "956",
              label: "ابو الحمام المتوسط (78)",
              icon: null,
              search_field:
                "ابو الحمام المتوسط (78) abu al-hamam al-motawasit (78)",
              group_label: null,
            },
            {
              id: "960",
              label: "ابو السوس (5)",
              icon: null,
              search_field: "ابو السوس (5) abu al-soos (5)",
              group_label: null,
            },
            {
              id: "964",
              label: "ابو قديس الشيوح (51)",
              icon: null,
              search_field: "ابو قديس الشيوح (51) abu qdeis al-shoyoh (51)",
              group_label: null,
            },
            {
              id: "968",
              label: "ابو قديس الصماديه (50)",
              icon: null,
              search_field: "ابو قديس الصماديه (50) abu qdeis al-smadiya (50)",
              group_label: null,
            },
            {
              id: "972",
              label: "ابو قديس الغربي (52)",
              icon: null,
              search_field: "ابو قديس الغربي (52) abu qdeis al-gharbi (52)",
              group_label: null,
            },
            {
              id: "976",
              label: "البسيس الجنوبي (21)",
              icon: null,
              search_field: "البسيس الجنوبي (21) al-basees al-janoubi (21)",
              group_label: null,
            },
            {
              id: "980",
              label: "البلد (27)",
              icon: null,
              search_field: "البلد (27) al-balad (27)",
              group_label: null,
            },
            {
              id: "996",
              label: "الخلايل (13)",
              icon: null,
              search_field: "الخلايل (13) al-khalayel (13)",
              group_label: null,
            },
            {
              id: "1000",
              label: "الشقفان (17)",
              icon: null,
              search_field: "الشقفان (17) al-shqfan (17)",
              group_label: null,
            },
            {
              id: "1004",
              label: "الشيخ فلاح (57)",
              icon: null,
              search_field: "الشيخ فلاح (57) al-shaikh falah (57)",
              group_label: null,
            },
            {
              id: "1008",
              label: "العباره (28)",
              icon: null,
              search_field: "العباره (28) al-'abbara (28)",
              group_label: null,
            },
            {
              id: "1012",
              label: "العصارة (6)",
              icon: null,
              search_field: "العصاره (6) al-'assara (6)",
              group_label: null,
            },
            {
              id: "1016",
              label: "العصارة الشمالية (3)",
              icon: null,
              search_field: "العصاره الشماليه (3) al-'assa al-shamaliya (3)",
              group_label: null,
            },
            {
              id: "1020",
              label: "العوجا (15)",
              icon: null,
              search_field: "العوجا (15) al-'oja (15)",
              group_label: null,
            },
            {
              id: "1024",
              label: "الكنيسة (39)",
              icon: null,
              search_field: "الكنيسه (39) al-kanissah (39)",
              group_label: null,
            },
            {
              id: "1028",
              label: "المرج الشرقي (88)",
              icon: null,
              search_field: "المرج الشرقي (88) al-marj al-sharqi (88)",
              group_label: null,
            },
            {
              id: "1032",
              label: "المشحنة الشرقي (11)",
              icon: null,
              search_field: "المشحنه الشرقي (11) al-mashhana al-sharqi (11)",
              group_label: null,
            },
            {
              id: "1036",
              label: "المشحنة الغربي (10)",
              icon: null,
              search_field: "المشحنه الغربي (10) al-mashhana al-gharbi (10)",
              group_label: null,
            },
            {
              id: "1040",
              label: "المقاتي (37)",
              icon: null,
              search_field: "المقاتي (37) al-maqati (37)",
              group_label: null,
            },
            {
              id: "1044",
              label: "الملس  الشرقي (73)",
              icon: null,
              search_field: "الملس  الشرقي (73) al-mals al-sharqi (73)",
              group_label: null,
            },
            {
              id: "1048",
              label: "الملس  الغربي (69)",
              icon: null,
              search_field: "الملس  الغربي (69) al-mals al-gharbi (69)",
              group_label: null,
            },
            {
              id: "1052",
              label: "المنصيه الجنوبي (87)",
              icon: null,
              search_field: "المنصيه الجنوبي (87) al-mansiya al-janoubi (87)",
              group_label: null,
            },
            {
              id: "1056",
              label: "المنصيه الشمالي (86)",
              icon: null,
              search_field: "المنصيه الشمالي (86) al-mansiya al-shamali (86)",
              group_label: null,
            },
            {
              id: "1060",
              label: "النويحر الشرقي (44)",
              icon: null,
              search_field: "النويحر الشرقي (44) al-nwihir al-sharqi (44)",
              group_label: null,
            },
            {
              id: "1064",
              label: "النويحر الغربي (30)",
              icon: null,
              search_field: "النويحر الغربي (30) al-nwihir al-gharbi (30)",
              group_label: null,
            },
            {
              id: "1068",
              label: "النويحر الوسطاني (41)",
              icon: null,
              search_field: "النويحر الوسطاني (41) al-nwihir al-wastani (41)",
              group_label: null,
            },
            {
              id: "1072",
              label: "ام البطم (64)",
              icon: null,
              search_field: "ام البطم (64) um al-batm (64)",
              group_label: null,
            },
            {
              id: "1076",
              label: "ام الشبرق (55)",
              icon: null,
              search_field: "ام الشبرق (55) um al-shobroq (55)",
              group_label: null,
            },
            {
              id: "1080",
              label: "ام العدس (48)",
              icon: null,
              search_field: "ام العدس (48) um al-'adas (48)",
              group_label: null,
            },
            {
              id: "1084",
              label: "ام المعاصر (54)",
              icon: null,
              search_field: "ام المعاصر (54) um al-m'aser (54)",
              group_label: null,
            },
            {
              id: "1088",
              label: "ام صراره الشرقي (79)",
              icon: null,
              search_field: "ام صراره الشرقي (79) um sararah al-sharqi (79)",
              group_label: null,
            },
            {
              id: "1092",
              label: "ام صراره الغربي (70)",
              icon: null,
              search_field: "ام صراره الغربي (70) um sararah al-gharbi (70)",
              group_label: null,
            },
            {
              id: "1096",
              label: "بسيس  الشيوخ (20)",
              icon: null,
              search_field: "بسيس  الشيوخ (20) bseis al-shoyookh (20)",
              group_label: null,
            },
            {
              id: "1100",
              label: "بسيس  الصماديه (19)",
              icon: null,
              search_field: "بسيس  الصماديه (19) bseis al-smadiya (19)",
              group_label: null,
            },
            {
              id: "1104",
              label: "بيدر العقيلي (38)",
              icon: null,
              search_field: "بيدر العقيلي (38) baydar al'aqelei (38)",
              group_label: null,
            },
            {
              id: "1108",
              label: "تلاع السيح (14)",
              icon: null,
              search_field: "تلاع السيح (14) tla' al-seeh (14)",
              group_label: null,
            },
            {
              id: "1112",
              label: "تلول الشيوخ (43)",
              icon: null,
              search_field: "تلول الشيوخ (43) tolool al-shoyookh (43)",
              group_label: null,
            },
            {
              id: "1116",
              label: "تلول الصماديه (35)",
              icon: null,
              search_field: "تلول الصماديه (35) tolool al-smadiya (35)",
              group_label: null,
            },
            {
              id: "1120",
              label: "تلول حلوش (34)",
              icon: null,
              search_field: "تلول حلوش (34) tolool halwash (34)",
              group_label: null,
            },
            {
              id: "1124",
              label: "تلول حماشا (89)",
              icon: null,
              search_field: "تلول حماشا (89) tolool hamasha (89)",
              group_label: null,
            },
            {
              id: "1128",
              label: "حاطم (29)",
              icon: null,
              search_field: "حاطم (29) hatim (29)",
              group_label: null,
            },
            {
              id: "1132",
              label: "حمام ام البسيس  الصماديه (23)",
              icon: null,
              search_field:
                "حمام ام البسيس  الصماديه (23) hammam um al-bseis al-smadiya (23)",
              group_label: null,
            },
            {
              id: "1136",
              label: "حمام ام البسيس الشمالي (22)",
              icon: null,
              search_field:
                "حمام ام البسيس الشمالي (22) hammam um al-bseis al-shamali (22)",
              group_label: null,
            },
            {
              id: "1140",
              label: "حمام ام بسيس الشيوخ (24)",
              icon: null,
              search_field:
                "حمام ام بسيس الشيوخ (24) hammam um bseis shoyookh (24)",
              group_label: null,
            },
            {
              id: "1144",
              label: "حمام بسيس الجنوبي (25)",
              icon: null,
              search_field:
                "حمام بسيس الجنوبي (25) hammam um bseis al-janoubi (25)",
              group_label: null,
            },
            {
              id: "1148",
              label: "خربة يعمون (56)",
              icon: null,
              search_field: "خربه يعمون (56) khirbat ya'moun (56)",
              group_label: null,
            },
            {
              id: "1152",
              label: "خلة البئر (66)",
              icon: null,
              search_field: "خله البئر (66) khallat al-bi'ar (66)",
              group_label: null,
            },
            {
              id: "1156",
              label: "دبة النمر (1)",
              icon: null,
              search_field: "دبه النمر (1) dobbat al-nimr (1)",
              group_label: null,
            },
            {
              id: "1160",
              label: "دواقير ابو الحمام (68)",
              icon: null,
              search_field: "دواقير ابو الحمام (68) dawaqeer abu al-hamam (68)",
              group_label: null,
            },
            {
              id: "1164",
              label: "دواقير ابو الحمام الشمالية (67)",
              icon: null,
              search_field:
                "دواقير ابو الحمام الشماليه (67) dawaqeer abu al-hamam al-shamaliya (67)",
              group_label: null,
            },
            {
              id: "1168",
              label: "دوحلا الشرقي (7)",
              icon: null,
              search_field: "دوحلا الشرقي (7) dohla al-sharqi (7)",
              group_label: null,
            },
            {
              id: "1172",
              label: "دوحلا الغربي (8)",
              icon: null,
              search_field: "دوحلا الغربي (8) dohla al-gharbi (8)",
              group_label: null,
            },
            {
              id: "1176",
              label: "ذراع كبر الجنوبي (85)",
              icon: null,
              search_field: "ذراع كبر الجنوبي (85) dra'a kebr al-janoubi (85)",
              group_label: null,
            },
            {
              id: "1180",
              label: "ذراع كبر الشمالي (84)",
              icon: null,
              search_field: "ذراع كبر الشمالي (84) dra'a kebr al-shamali (84)",
              group_label: null,
            },
            {
              id: "1184",
              label: "سهام السناد (65)",
              icon: null,
              search_field: "سهام السناد (65) siham al-sanad (65)",
              group_label: null,
            },
            {
              id: "1188",
              label: "شعب الامين (16)",
              icon: null,
              search_field: "شعب الامين (16) sha'ab al-ameen (16)",
              group_label: null,
            },
            {
              id: "1192",
              label: "شياحه (53)",
              icon: null,
              search_field: "شياحه (53) shiyaha (53)",
              group_label: null,
            },
            {
              id: "1196",
              label: "عبارة الشيوخ (36)",
              icon: null,
              search_field: "عباره الشيوخ (36) abbarat al-shoyookh (36)",
              group_label: null,
            },
            {
              id: "1200",
              label: "عصارة تلاع الكرك (4)",
              icon: null,
              search_field: "عصاره تلاع الكرك (4) assart tla' al-karak (4)",
              group_label: null,
            },
            {
              id: "1204",
              label: "غزى (81)",
              icon: null,
              search_field: "غزي (81) ghaza (81)",
              group_label: null,
            },
            {
              id: "1208",
              label: "قطع يونس (40)",
              icon: null,
              search_field: "قطع يونس (40) qat' younes (40)",
              group_label: null,
            },
            {
              id: "1212",
              label: "قطعة الجامع (12)",
              icon: null,
              search_field: "قطعه الجامع (12) qit'at al-jami' (12)",
              group_label: null,
            },
            {
              id: "1216",
              label: "كسارة مفلح (2)",
              icon: null,
              search_field: "كساره مفلح (2) kassarat meflih (2)",
              group_label: null,
            },
            {
              id: "1220",
              label: "مرآة العين (9)",
              icon: null,
              search_field: "مراه العين (9) mira'at al-ein (9)",
              group_label: null,
            },
            {
              id: "1224",
              label: "مرج الزعبي الجنوبي (61)",
              icon: null,
              search_field:
                "مرج الزعبي الجنوبي (61) marj al-zoubi al-janoubi (61)",
              group_label: null,
            },
            {
              id: "1228",
              label: "مرج الزعبي الشمالي (58)",
              icon: null,
              search_field:
                "مرج الزعبي الشمالي (58) marj al-zoubi al-shamali (58)",
              group_label: null,
            },
            {
              id: "1232",
              label: "مرج الزعبي الصماديه (59)",
              icon: null,
              search_field:
                "مرج الزعبي الصماديه (59) marj al-zoubi al-smadiya (59)",
              group_label: null,
            },
            {
              id: "1236",
              label: "مرج الشيوخ (74)",
              icon: null,
              search_field: "مرج الشيوخ (74) marj al-shoyookh (74)",
              group_label: null,
            },
            {
              id: "1240",
              label: "مرج الصماديه (80)",
              icon: null,
              search_field: "مرج الصماديه (80) marj al-smadiya (80)",
              group_label: null,
            },
            {
              id: "1244",
              label: "مرج الوقفي (42)",
              icon: null,
              search_field: "مرج الوقفي (42) marj al-waqfi (42)",
              group_label: null,
            },
            {
              id: "1248",
              label: "مرج بركات (31)",
              icon: null,
              search_field: "مرج بركات (31) marj barakat (31)",
              group_label: null,
            },
            {
              id: "1252",
              label: "مرج حلوش (71)",
              icon: null,
              search_field: "مرج حلوش (71) marj haloosh (71)",
              group_label: null,
            },
            {
              id: "1256",
              label: "مرج زعبي الشيوخ (60)",
              icon: null,
              search_field: "مرج زعبي الشيوخ (60) marj zo'bi al-shoyookh (60)",
              group_label: null,
            },
            {
              id: "1260",
              label: "مرج مريان (49)",
              icon: null,
              search_field: "مرج مريان (49) marj mariyan (49)",
              group_label: null,
            },
            {
              id: "1266",
              label: "نوحير الدواقير (46)",
              icon: null,
              search_field: "نوحير الدواقير (46) noheer al-dawaqeer (46)",
              group_label: null,
            },
            {
              id: "1270",
              label: "نويحر الجنوبي (33)",
              icon: null,
              search_field: "نويحر الجنوبي (33) noheer al-janoubi (33)",
              group_label: null,
            },
            {
              id: "1274",
              label: "نويحر الشيوخ (45)",
              icon: null,
              search_field: "نويحر الشيوخ (45) nwihir al-shoyookh (45)",
              group_label: null,
            },
            {
              id: "1278",
              label: "نويحر الطويل (32)",
              icon: null,
              search_field: "نويحر الطويل (32) nwihir al-taweel (32)",
              group_label: null,
            },
            {
              id: "1282",
              label: "نويحر القصير (47)",
              icon: null,
              search_field: "نويحر القصير (47) nwihir al-qaseer (47)",
              group_label: null,
            },
            {
              id: "1286",
              label: "وادي القرين (63)",
              icon: null,
              search_field: "وادي القرين (63) wadi al-qareen (63)",
              group_label: null,
            },
            {
              id: "1290",
              label: "وادي الهنداوي (62)",
              icon: null,
              search_field: "وادي الهنداوي (62) wadi al-hindawi (62)",
              group_label: null,
            },
            {
              id: "1294",
              label: "وادي الورد (72)",
              icon: null,
              search_field: "وادي الورد (72) wadi al-ward (72)",
              group_label: null,
            },
            {
              id: "1298",
              label: "وادي حسان (26)",
              icon: null,
              search_field: "وادي حسان (26) wadi hassan (26)",
              group_label: null,
            },
            {
              id: "1302",
              label: "وران الشيوخ (82)",
              icon: null,
              search_field: "وران الشيوخ (82) woran al-shoyookh (82)",
              group_label: null,
            },
            {
              id: "1306",
              label: "وران الصماديه (83)",
              icon: null,
              search_field: "وران الصماديه (83) woran al-smadiya (83)",
              group_label: null,
            },
          ],
        },
        {
          id: "1310",
          label: "ام الابار (181)",
          icon: null,
          search_field: "ام الابار (181) um al-abar (181)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "1324",
          label: "ايدون (173)",
          icon: null,
          search_field: "ايدون (173) aydoun (173)",
          group_label: null,
          alhodlist: [
            {
              id: "1326",
              label: "ابو عوسية الغربية (19)",
              icon: null,
              search_field:
                "ابو عوسيه الغربيه (19) abu o'ssiya al-gharbiya (19)",
              group_label: null,
            },
            {
              id: "1330",
              label: "البلد (36)",
              icon: null,
              search_field: "البلد (36) al-balad (36)",
              group_label: null,
            },
            {
              id: "1340",
              label: "الجزيرة الغربية (8)",
              icon: null,
              search_field: "الجزيره الغربيه (8) al-jazeera al-gharbiya (8)",
              group_label: null,
            },
            {
              id: "1344",
              label: "الجزيرة الوسطانية (7)",
              icon: null,
              search_field: "الجزيره الوسطانيه (7) al-jazeera al-wastaniya (7)",
              group_label: null,
            },
            {
              id: "1348",
              label: "الجزيره الشرقية (6)",
              icon: null,
              search_field: "الجزيره الشرقيه (6) al-jazeera al-sahrqiya (6)",
              group_label: null,
            },
            {
              id: "1352",
              label: "الحجوى الشمالية (21)",
              icon: null,
              search_field: "الحجوي الشماليه (21) al-hajwa al-shamaliya (21)",
              group_label: null,
            },
            {
              id: "1356",
              label: "الحجيوي الوسطاني (25)",
              icon: null,
              search_field: "الحجيوي الوسطاني (25) al-hjiwi al-wastani (25)",
              group_label: null,
            },
            {
              id: "1360",
              label: "الخارجه (26)",
              icon: null,
              search_field: "الخارجه (26) al-kharjah (26)",
              group_label: null,
            },
            {
              id: "1374",
              label: "الخزينة (31)",
              icon: null,
              search_field: "الخزينه (31) al-khazina (31)",
              group_label: null,
            },
            {
              id: "1378",
              label: "الطوال (1)",
              icon: null,
              search_field: "الطوال (1) al-tawal (1)",
              group_label: null,
            },
            {
              id: "1382",
              label: "العوامية الجنوبية (33)",
              icon: null,
              search_field:
                "العواميه الجنوبيه (33) al-awamiya al-janoubiya (33)",
              group_label: null,
            },
            {
              id: "1386",
              label: "العوامية الشرقية (32)",
              icon: null,
              search_field: "العواميه الشرقيه (32) al-awamiya al-sharqiya (32)",
              group_label: null,
            },
            {
              id: "1390",
              label: "العوامية الغربية (29)",
              icon: null,
              search_field: "العواميه الغربيه (29) al-awamiya al-gharbiya (29)",
              group_label: null,
            },
            {
              id: "1394",
              label: "العيون (11)",
              icon: null,
              search_field: "العيون (11) al-oyoon (11)",
              group_label: null,
            },
            {
              id: "1398",
              label: "الغرابية (22)",
              icon: null,
              search_field: "الغرابيه (22) al-ghorabiya (22)",
              group_label: null,
            },
            {
              id: "1402",
              label: "الفحص (2)",
              icon: null,
              search_field: "الفحص (2) al-fahs (2)",
              group_label: null,
            },
            {
              id: "1406",
              label: "الماصية الشرقية (20)",
              icon: null,
              search_field: "الماصيه الشرقيه (20) al-masiya al-sharqiya (20)",
              group_label: null,
            },
            {
              id: "1410",
              label: "المعترض (4)",
              icon: null,
              search_field: "المعترض (4) al-mo'tarid (4)",
              group_label: null,
            },
            {
              id: "1414",
              label: "الملتقى (3)",
              icon: null,
              search_field: "الملتقي (3) al-moltaqa (3)",
              group_label: null,
            },
            {
              id: "1418",
              label: "النفلة (9)",
              icon: null,
              search_field: "النفله (9) al-nafla (9)",
              group_label: null,
            },
            {
              id: "1422",
              label: "الهداف التحتاني (13)",
              icon: null,
              search_field: "الهداف التحتاني (13) al-hadaf al-tahtani (13)",
              group_label: null,
            },
            {
              id: "1426",
              label: "الهداف الفوقاني (14)",
              icon: null,
              search_field: "الهداف الفوقاني (14) al-hadaf al-foqani (14)",
              group_label: null,
            },
            {
              id: "1430",
              label: "الوطية (17)",
              icon: null,
              search_field: "الوطيه (17) al-watiya (17)",
              group_label: null,
            },
            {
              id: "1434",
              label: "الوقف (28)",
              icon: null,
              search_field: "الوقف (28) al-waqf (28)",
              group_label: null,
            },
            {
              id: "1438",
              label: "رباع الشومر (12)",
              icon: null,
              search_field: "رباع الشومر (12) rba'a al-shomar (12)",
              group_label: null,
            },
            {
              id: "1442",
              label: "صدر الحزينة الشرقية (15)",
              icon: null,
              search_field:
                "صدر الحزينه الشرقيه (15) sadr al-hazina al-sharqiya (15)",
              group_label: null,
            },
            {
              id: "1446",
              label: "صدر الحزينة الغربية (16)",
              icon: null,
              search_field:
                "صدر الحزينه الغربيه (16) sadr al-hazina al-gharbiya (16)",
              group_label: null,
            },
            {
              id: "1450",
              label: "صرصره (30)",
              icon: null,
              search_field: "صرصره (30) sarsarah (30)",
              group_label: null,
            },
            {
              id: "1454",
              label: "عالم (10)",
              icon: null,
              search_field: "عالم (10) a'lem (10)",
              group_label: null,
            },
            {
              id: "1458",
              label: "عرقان هلاله (27)",
              icon: null,
              search_field: "عرقان هلاله (27) irqan hilala (27)",
              group_label: null,
            },
            {
              id: "1462",
              label: "عوسية الشرقية (18)",
              icon: null,
              search_field: "عوسيه الشرقيه (18) osia al-sharqiya (18)",
              group_label: null,
            },
            {
              id: "1466",
              label: "كريزم (5)",
              icon: null,
              search_field: "كريزم (5) krizem (5)",
              group_label: null,
            },
            {
              id: "1470",
              label: "ماصية قرن الجاموس (23)",
              icon: null,
              search_field:
                "ماصيه قرن الجاموس (23) masiyat qarn al-jamoos (23)",
              group_label: null,
            },
            {
              id: "1474",
              label: "وعر قرن الجاموس (24)",
              icon: null,
              search_field: "وعر قرن الجاموس (24) we'r qarn al-jamoos (24)",
              group_label: null,
            },
          ],
        },
        {
          id: "1478",
          label: "بشرى (182)",
          icon: null,
          search_field: "بشري (182) bushra (182)",
          group_label: null,
          alhodlist: [ {
            "id": "1480",
            "label": "الباب (9)",
            "icon": null,
            "search_field": "الباب (9) al-bab (9)",
            "group_label": null
        },
        {
            "id": "1484",
            "label": "البرنس (7)",
            "icon": null,
            "search_field": "البرنس (7) al-prince (7)",
            "group_label": null
        },
        {
            "id": "1488",
            "label": "البقعة (30)",
            "icon": null,
            "search_field": "البقعه (30) al-baqa'a (30)",
            "group_label": null
        },
        {
            "id": "1492",
            "label": "البلد (24)",
            "icon": null,
            "search_field": "البلد (24) al-balad (24)",
            "group_label": null
        },
        {
            "id": "1522",
            "label": "البوره (22)",
            "icon": null,
            "search_field": "البوره (22) al-boora (22)",
            "group_label": null
        },
        {
            "id": "1526",
            "label": "البيدر (28)",
            "icon": null,
            "search_field": "البيدر (28) al-beidar (28)",
            "group_label": null
        },
        {
            "id": "1530",
            "label": "الجزيرة (21)",
            "icon": null,
            "search_field": "الجزيره (21) al-jazeera (21)",
            "group_label": null
        },
        {
            "id": "1534",
            "label": "الجوخ (34)",
            "icon": null,
            "search_field": "الجوخ (34) al-jookh (34)",
            "group_label": null
        },
        {
            "id": "1538",
            "label": "الحزريه (25)",
            "icon": null,
            "search_field": "الحزريه (25) al-hezriya (25)",
            "group_label": null
        },
        {
            "id": "1542",
            "label": "الحلان (13)",
            "icon": null,
            "search_field": "الحلان (13) al-hallan (13)",
            "group_label": null
        },
        {
            "id": "1546",
            "label": "الحمص (17)",
            "icon": null,
            "search_field": "الحمص (17) al-hommos (17)",
            "group_label": null
        },
        {
            "id": "1550",
            "label": "الحوطه (15)",
            "icon": null,
            "search_field": "الحوطه (15) al-hoota (15)",
            "group_label": null
        },
        {
            "id": "1554",
            "label": "الخله (16)",
            "icon": null,
            "search_field": "الخله (16) al-khallah (16)",
            "group_label": null
        },
        {
            "id": "1558",
            "label": "الدراج (29)",
            "icon": null,
            "search_field": "الدراج (29) al-daraj (29)",
            "group_label": null
        },
        {
            "id": "1562",
            "label": "الدواقير (26)",
            "icon": null,
            "search_field": "الدواقير (26) al-dawaqeer (26)",
            "group_label": null
        },
        {
            "id": "1566",
            "label": "الرجوم السود الجنوبي (12)",
            "icon": null,
            "search_field": "الرجوم السود الجنوبي (12) al-rjoom al-sood al-janoubi (12)",
            "group_label": null
        },
        {
            "id": "1570",
            "label": "الرجوم السود الشمالي (6)",
            "icon": null,
            "search_field": "الرجوم السود الشمالي (6) al-rjoom al-sood al-shamali (6)",
            "group_label": null
        },
        {
            "id": "1574",
            "label": "السياف (1)",
            "icon": null,
            "search_field": "السياف (1) al-sayyaf (1)",
            "group_label": null
        },
        {
            "id": "1578",
            "label": "الشراري (18)",
            "icon": null,
            "search_field": "الشراري (18) al-sharari (18)",
            "group_label": null
        },
        {
            "id": "1582",
            "label": "الصدار (33)",
            "icon": null,
            "search_field": "الصدار (33) al-sadar (33)",
            "group_label": null
        },
        {
            "id": "1586",
            "label": "العزمه (37)",
            "icon": null,
            "search_field": "العزمه (37) al-azmah (37)",
            "group_label": null
        },
        {
            "id": "1590",
            "label": "القسيس  الشمالي (8)",
            "icon": null,
            "search_field": "القسيس  الشمالي (8) al-qsseis al-shamali (8)",
            "group_label": null
        },
        {
            "id": "1594",
            "label": "القسيس الجنوبي (10)",
            "icon": null,
            "search_field": "القسيس الجنوبي (10) al-qsseis al-janoubi (10)",
            "group_label": null
        },
        {
            "id": "1598",
            "label": "الكرسنه الشرقي (2)",
            "icon": null,
            "search_field": "الكرسنه الشرقي (2) al-karsanah - al-sharqi (2)",
            "group_label": null
        },
        {
            "id": "1602",
            "label": "الكرسنه الغربي (3)",
            "icon": null,
            "search_field": "الكرسنه الغربي (3) al-karsanah al-gharbi (3)",
            "group_label": null
        },
        {
            "id": "1606",
            "label": "الكرم (23)",
            "icon": null,
            "search_field": "الكرم (23) al-karm (23)",
            "group_label": null
        },
        {
            "id": "1610",
            "label": "المجوز (35)",
            "icon": null,
            "search_field": "المجوز (35) al-mejwiz (35)",
            "group_label": null
        },
        {
            "id": "1614",
            "label": "المخنق (4)",
            "icon": null,
            "search_field": "المخنق (4) al-makhnaq (4)",
            "group_label": null
        },
        {
            "id": "1618",
            "label": "المسحلانية (32)",
            "icon": null,
            "search_field": "المسحلانيه (32) al-mashalaniya (32)",
            "group_label": null
        },
        {
            "id": "1622",
            "label": "المغاره (5)",
            "icon": null,
            "search_field": "المغاره (5) al-maghara (5)",
            "group_label": null
        },
        {
            "id": "1626",
            "label": "المقرمه (20)",
            "icon": null,
            "search_field": "المقرمه (20) al-magrama (20)",
            "group_label": null
        },
        {
            "id": "1630",
            "label": "حوض  الدن (36)",
            "icon": null,
            "search_field": "حوض  الدن (36) hod al-don (36)",
            "group_label": null
        },
        {
            "id": "1634",
            "label": "دغيم (19)",
            "icon": null,
            "search_field": "دغيم (19) dgheim (19)",
            "group_label": null
        },
        {
            "id": "1638",
            "label": "سليم (11)",
            "icon": null,
            "search_field": "سليم (11) saleem (11)",
            "group_label": null
        },
        {
            "id": "1642",
            "label": "غياضه (31)",
            "icon": null,
            "search_field": "غياضه (31) ghaiyada (31)",
            "group_label": null
        },
        {
            "id": "1646",
            "label": "مارس  حمده (27)",
            "icon": null,
            "search_field": "مارس  حمده (27) mars hamda (27)",
            "group_label": null
        },
        {
            "id": "1650",
            "label": "مخر النجم (14)",
            "icon": null,
            "search_field": "مخر النجم (14) makhr al-nijm (14)",
            "group_label": null
        }],
        },
        {
          id: "1654",
          label: "بيت راس (183)",
          icon: null,
          search_field: "بيت راس (183) bayt ras (183)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "1708",
          label: "بيت يافا (184)",
          icon: null,
          search_field: "بيت يافا (184) bayt yafa (184)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "1814",
          label: "تقبل (185)",
          icon: null,
          search_field: "تقبل (185) taqbal (185)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "1862",
          label: "ججين (186)",
          icon: null,
          search_field: "ججين (186) jejin (186)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "1894",
          label: "جمحه (187)",
          icon: null,
          search_field: "جمحه (187) jamha (187)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "1936",
          label: "حكما (188)",
          icon: null,
          search_field: "حكما (188) hakma (188)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "2008",
          label: "حواره (189)",
          icon: null,
          search_field: "حواره (189) hawara (189)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "2140",
          label: "حور (190)",
          icon: null,
          search_field: "حور (190) hoor (190)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "2196",
          label: "حوفا الوسطيه (191)",
          icon: null,
          search_field: "حوفا الوسطيه (191) hofa al-wasatiya (191)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "2248",
          label: "دوقره (192)",
          icon: null,
          search_field: "دوقره (192) doqarah (192)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "2322",
          label: "زبدة فركوح (193)",
          icon: null,
          search_field: "زبده فركوح (193) zabda farkouh (193)",
          group_label: null,
          alhodlist: [  {
            "id": "2324",
            "label": "السريج (7)",
            "icon": null,
            "search_field": "السريج (7) al-sareej (7)",
            "group_label": null
        },
        {
            "id": "2338",
            "label": "الظهر (11)",
            "icon": null,
            "search_field": "الظهر (11) al-dhahr (11)",
            "group_label": null
        },
        {
            "id": "2356",
            "label": "الفحص (10)",
            "icon": null,
            "search_field": "الفحص (10) al-fahs (10)",
            "group_label": null
        },
        {
            "id": "2374",
            "label": "القناص (9)",
            "icon": null,
            "search_field": "القناص (9) al-qannas (9)",
            "group_label": null
        },
        {
            "id": "2378",
            "label": "المعترض (8)",
            "icon": null,
            "search_field": "المعترض (8) al-mo'tarid (8)",
            "group_label": null
        },
        {
            "id": "2394",
            "label": "جريته (1)",
            "icon": null,
            "search_field": "جريته (1) jraita (1)",
            "group_label": null
        },
        {
            "id": "2398",
            "label": "عبادة (12)",
            "icon": null,
            "search_field": "عباده (12) obada (12)",
            "group_label": null
        }],
        },
        {
          id: "2412",
          label: "زحر (194)",
          icon: null,
          search_field: "زحر (194) zahar (194)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "2460",
          label: "سال (195)",
          icon: null,
          search_field: "سال (195) sal (195)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "2540",
          label: "سوم (196)",
          icon: null,
          search_field: "سوم (196) sum (196)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "2618",
          label: "شطنا (197)",
          icon: null,
          search_field: "شطنا (197) shatna (197)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "2700",
          label: "صيدور (198)",
          icon: null,
          search_field: "صيدور (198) saidoor (198)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "2744",
          label: "علعال (199)",
          icon: null,
          search_field: "علعال (199) al'al (199)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "2824",
          label: "فوعره (200)",
          icon: null,
          search_field: "فوعره (200) fo'ara (200)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "2900",
          label: "قم (201)",
          icon: null,
          search_field: "قم (201) qum (201)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "2940",
          label: "قميم (202)",
          icon: null,
          search_field: "قميم (202) qumaym (202)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "2988",
          label: "كبر (203)",
          icon: null,
          search_field: "كبر (203) kabr (203)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "3026",
          label: "كتم (204)",
          icon: null,
          search_field: "كتم (204) ketem (204)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "3104",
          label: "كفر اسد (205)",
          icon: null,
          search_field: "كفر اسد (205) kufr asad (205)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "3254",
          label: "كفر جايز (206)",
          icon: null,
          search_field: "كفر جايز (206) kufr jayez (206)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "3314",
          label: "كفر رحتا (207)",
          icon: null,
          search_field: "كفر رحتا (207) kufr rahta (207)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "3362",
          label: "كفر عان (208)",
          icon: null,
          search_field: "كفر عان (208) kufr a'an (208)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "3396",
          label: "كفر يوبا (209)",
          icon: null,
          search_field: "كفر يوبا (209) kufryoba (209)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "3524",
          label: "مرو (178)",
          icon: null,
          search_field: "مرو (178) maru (178)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "3582",
          label: "مزرعة تميره (210)",
          icon: null,
          search_field: "مزرعه تميره (210) mazra'at tamerah (210)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "3684",
          label: "ناطفه (211)",
          icon: null,
          search_field: "ناطفه (211) natfeh (211)",
          group_label: null,
          alhodlist: [],
        },
        {
          id: "3766",
          label: "هام (213)",
          icon: null,
          search_field: "هام (213) ham (213)",
          group_label: null,
          alhodlist: [],
        },
      ],
    },
  ],
};
